#Server socket
server.ws.port=8686
server.tcp.port=8889
server.udp.port=8890
server.id=1
server.type=ws

#number threads queue
server.queue.threads.size=50
server.queue.threads.queue.size=200

#number threads socket
server.socket.threads.size=10
server.socket.queue.size=50


# Public key
server.public.key=T7PfKrPGvK

# Queue
queue.username=guest
queue.virtualHost=/
queue.password=guest
queue.port=5672
queue.ip=localhost
queue.video.process=ITCAREER_QUEUE_PROCESS_VIDEO
queue.video.pushback=ITCAREER_QUEUE_MEDIA_COMPLETED_PROCESS_VIDEO
queue.notification = ITCAREER_QUEUE_NOTIFICATION
queue.msg.app=SOCKET_APP

file.upload-dir=D:\\uploads

video.ts.second.default=10