#Server socket
server.ws.port=8686
server.tcp.port=8889
server.udp.port=8890
server.id=1
server.type=ws

#number threads queue
server.queue.threads.size=50
server.queue.threads.queue.size=200

#number threads socket
server.socket.threads.size=10
server.socket.queue.size=50


# Public key
server.public.key=T7PfKrPGvK

# Queue
queue.username=admin
queue.virtualHost=/
queue.password=admin@2o23.hcm
queue.port=5672
queue.ip=192.168.0.10
queue.subscribe=QUEUE_PROCESS_VIDEO_DEMO
queue.pushback=QUEUE_MEDIA_COMPLETED_PROCESS_VIDEO_DEMO
queue.msg.app=VIDEO_APP

file.upload-dir=/uploads

video.ts.second.default=10